camel:
  springboot:
    # The Camel context name
    name: FisRestSQL

# Binding health checks to a different port
management:
  port: 8091
  
server:
  port: 8090

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true
  
activemq:
  host: broker-amq-headless-amq7-raif.apps.box.it-speeltuin.nl
  port: 443
  username: amq-demo-user
  password: passw0rd
  clientId: demoConsumerClient

topic:
  name: demoTopic
  subcsribtionName: demoSubcsribtion
  
apiContext: /api

apidoc:
  host: 0.0.0.0
  port: ${server.port}
